domain: localhost:3000
facebook: 
  APP_ID: 475369315845616
  APP_SECRET: 13ce8ab6e56eaed6afd65bff058356fd

google:
  CLIENT-ID: 271010057916-1trnf3jshio9o8stck4orj7cnuhbvonp.apps.googleusercontent.com
  CLIENT-SECRET: bCEvMJQHYLJ0PIQFWm_gQAxY