domain: http://foodies-test-deployment.herokuapp.com
facebook: 
  APP_ID: 475369315845616
  APP_SECRET: 13ce8ab6e56eaed6afd65bff058356fd

google:
  CLIENT-ID: 271010057916.apps.googleusercontent.com
  CLIENT-SECRET: UCqqQnzY2krmazxGuERdFUGf